swagger: "2.0"
info:
  version: "0.0.1"
  title: Image-Server

# during dev, should point to your local machine
host: localhost:3030
# basePath prefixes all resource paths
basePath: /

schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/html
paths:
  # api routes
  /api/test:
   $ref: "http://localhost:8089/test.yaml#/paths/~1api~1test"

  /api/test/hello:
   $ref: "http://localhost:8089/test.yaml#/paths/~1api~1test~1hello"

  /api/test/protected:
   $ref: "http://localhost:8089/test.yaml#/paths/~1api~1test~1protected"

# complex objects have schema definitions
# definitions:
